### ISSUE TITLE
Graphic output and touch input on wrong place

### ISSUE THREAD

**Issue by Xean** [spiffcode/hostile-takeover#1]
Hey!

I was happy to find the source code of this game here. But when I tried to run the game in the simulator, the game wasn't displayed at the right position. And even the "input field" isn't correct. I mean the coordinates of the touch event are interpreted wrong.
In this image I marked the position where I have to touch to get the play- and option button ressed, so you can see what I mean:
![error](https://cloud.githubusercontent.com/assets/1352796/7119718/0bdd920e-e208-11e4-92c0-89ac28903300.jpg)
(The white boxes aren't exact in size and position, but close enough)

I'm using the newes Xcode 6.3 (6D570), but didn't change anything. Just downloaded and run.

Did I do something wrong? Or is this a bug?

**Comment by N104** [comment]
Yeah, it's a bug. Try compiling the game with the iOS 7 SDK as the Base SDK. I believe it will then run on device/simulator under (but not including) iOS 8.3.

I believe the cause of the issue is because [UIScreen mainScreen].bounds became orientation specific in iOS 8.

**Comment by Xean** [comment]
You are right. It works with iOS 7.1. Thanks!
