### ISSUE TITLE
How about the server?

### ISSUE THREAD

**Issue by KevinMX** [spiffcode/hostile-takeover#3]
I've downloaded the android version and tried the game, and it's fine:) But Multiplayer mode is not working for me. I don't know if it's a network problem(I'm in China, Chinese network has a firewall which blocks google,fb and something else xD) or ur server has down. So why not let players ourselves to create our own servers? This would actually make this okd game live longer.

**Comment by N104** [comment]
The game server is running fine. The server uses Google App Engine, so if your firewall blocks Google services, then that's probably why you are unable to access multiplayer.

**Comment by KevinMX** [comment]
Got it. And I've seen the instruction to create a server, though I need to compile the whole game again. Closing issue.
